services:
  postgres:
    container_name: ps_sql
    image: postgres:17.4
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser
      #where we will set up our postgres data
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-keycloak:/var/lib/postgresql/data
    ports:
      - 5110:5432 # host_porte:container_port

    restart: unless-stopped
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: ps_sql
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: appuser
      KC_DB_PASSWORD: appuser
    command:
      - "start-dev"


volumes:
  postgres-keycloak:
