spring:
  application:
    name: keycloak-integration-spring
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/keycloak-integration
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8080
jwt:
  auth:
    converter:
      resource-id: keycloak-integration-api
      principale-attribute: preferred_username